### PR TITLE
Propagate Docker container exit code

### LINKED ISSUE #610: Docker executor does not propagate exit code
Failed commands from docker executor are not reported as "failed"

Example DAG:
```yaml
steps:
  - name: 'emulate-failure'
    command: ['false']
    executor:
      type: 'docker'
      config:
        image: 'ubuntu:24.04'
        host:
          AutoRemove: true
```

#### Expectation

The step is reported as `failed`:
image

#### Actual

The step is reported as `finished`:
image

### PR DESCRIPTION
**Pull request by x4204**
Fixes #610 

Status from docker executor is now correctly reported to Dagu on exit:
image

### CODE REVIEW

File: internal/dag/executor/docker.go [hunk 1]
```diff
@@ -88,6 +88,13 @@ func (e *docker) Run() error {
 		return err
 	}
 
+	defer func() {
+		if e.autoRemove {
+			err := cli.ContainerRemove(ctx, resp.ID, types.ContainerRemoveOptions{})
+			util.LogErr("docker executor: remove container", err)
+		}
+	}()
```
Comment (yohamta0) [inline internal/dag/executor/docker.go:96]: Great refactoring of the clean-up function. Thank you!

**Review by yohamta — APPROVED** [review]
✨✨LGTM✨✨🚀, thank you very much!
